# Generated by https://github.com/Cryptact/twirpy/tree/main/protoc-gen-twirpy.  DO NOT EDIT!
# source: proto/frey.proto

from typing import Any

from twirp.client import TwirpClient
from twirp.context import Context

from . import atoms_pb2 as _atoms_pb2
from . import frey_pb2 as _frey_pb2


class FreyClient(TwirpClient):
    def RequestRegistration(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.AuthRequestRegistrationPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _frey_pb2.AuthRequestRegistrationResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/RequestRegistration",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.AuthRequestRegistrationResponse,
            **kwargs,
        )

    def ApproveRegistration(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.AuthApproveRegistrationPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _frey_pb2.AuthApproveRegistrationResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/ApproveRegistration",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.AuthApproveRegistrationResponse,
            **kwargs,
        )

    def Authorize(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.AuthAuthorizePayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _frey_pb2.AuthAuthorizeResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/Authorize",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.AuthAuthorizeResponse,
            **kwargs,
        )

    def QuickAuthorize(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.AuthQuickAuthorizePayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _frey_pb2.AuthQuickAuthorizeResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/QuickAuthorize",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.AuthQuickAuthorizeResponse,
            **kwargs,
        )

    def Me(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.AuthMePayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _frey_pb2.AuthMeResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/Me",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.AuthMeResponse,
            **kwargs,
        )

    def DepersonalizeAccount(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.DepersonalizePayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/DepersonalizeAccount",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def ChangePassword(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.AuthChangePasswordPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _frey_pb2.AuthChangePasswordResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/ChangePassword",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.AuthChangePasswordResponse,
            **kwargs,
        )

    def RequestResetPassword(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.AuthRequestResetPasswordPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _frey_pb2.AuthRequestResetPasswordResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/RequestResetPassword",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.AuthRequestResetPasswordResponse,
            **kwargs,
        )

    def ApproveResetPassword(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.AuthApproveResetPasswordPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _frey_pb2.AuthApproveResetPasswordResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/ApproveResetPassword",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.AuthApproveResetPasswordResponse,
            **kwargs,
        )

    def UpdatePersonalInfo(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.PersonsUpdatePersonalInfoPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/UpdatePersonalInfo",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def GetPersonalInfo(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.PersonsGetPersonalInfoPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _frey_pb2.PersonsGetPersonalInfoResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/GetPersonalInfo",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.PersonsGetPersonalInfoResponse,
            **kwargs,
        )

    def FindByTenhouIds(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.PersonsFindByTenhouIdsPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _frey_pb2.PersonsFindByTenhouIdsResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/FindByTenhouIds",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.PersonsFindByTenhouIdsResponse,
            **kwargs,
        )

    def FindByMajsoulAccountId(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.PersonsFindByMajsoulIdsPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _frey_pb2.PersonsFindByTenhouIdsResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/FindByMajsoulAccountId",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.PersonsFindByTenhouIdsResponse,
            **kwargs,
        )

    def FindByTitle(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.PersonsFindByTitlePayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _frey_pb2.PersonsFindByTitleResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/FindByTitle",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.PersonsFindByTitleResponse,
            **kwargs,
        )

    def GetEventAdmins(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.AccessGetEventAdminsPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _frey_pb2.AccessGetEventAdminsResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/GetEventAdmins",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.AccessGetEventAdminsResponse,
            **kwargs,
        )

    def GetEventReferees(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.AccessGetEventRefereesPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _frey_pb2.AccessGetEventRefereesResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/GetEventReferees",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.AccessGetEventRefereesResponse,
            **kwargs,
        )

    def GetMajsoulNicknames(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.PersonsGetMajsoulNicknamesPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _frey_pb2.PersonsGetMajsoulNicknamesResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/GetMajsoulNicknames",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.PersonsGetMajsoulNicknamesResponse,
            **kwargs,
        )

    def GetSuperadminFlag(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.AccessGetSuperadminFlagPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _frey_pb2.AccessGetSuperadminFlagResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/GetSuperadminFlag",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.AccessGetSuperadminFlagResponse,
            **kwargs,
        )

    def GetOwnedEventIds(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.AccessGetOwnedEventIdsPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _frey_pb2.AccessGetOwnedEventIdsResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/GetOwnedEventIds",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.AccessGetOwnedEventIdsResponse,
            **kwargs,
        )

    def AddRuleForPerson(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.AccessAddRuleForPersonPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _frey_pb2.AccessAddRuleForPersonResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/AddRuleForPerson",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.AccessAddRuleForPersonResponse,
            **kwargs,
        )

    def DeleteRuleForPerson(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.AccessDeleteRuleForPersonPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/DeleteRuleForPerson",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def CreateAccount(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.PersonsCreateAccountPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _frey_pb2.PersonsCreateAccountResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/CreateAccount",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.PersonsCreateAccountResponse,
            **kwargs,
        )

    def GetNotificationsSettings(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.PersonsGetNotificationsSettingsPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _frey_pb2.PersonsGetNotificationsSettingsResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/GetNotificationsSettings",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.PersonsGetNotificationsSettingsResponse,
            **kwargs,
        )

    def SetNotificationsSettings(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.PersonsSetNotificationsSettingsPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Frey/SetNotificationsSettings",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )
