# Generated by https://github.com/Cryptact/twirpy/tree/main/protoc-gen-twirpy.  DO NOT EDIT!
# source: proto/frey.proto

from typing import Any

from aiohttp import ClientSession
from twirp.async_client import AsyncTwirpClient
from twirp.context import Context

from . import atoms_pb2 as _atoms_pb2
from . import frey_pb2 as _frey_pb2


class AsyncFreyClient(AsyncTwirpClient):
    async def RequestRegistration(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.AuthRequestRegistrationPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _frey_pb2.AuthRequestRegistrationResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Frey/RequestRegistration",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.AuthRequestRegistrationResponse,
            session=session,
            **kwargs,
        )

    async def ApproveRegistration(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.AuthApproveRegistrationPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _frey_pb2.AuthApproveRegistrationResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Frey/ApproveRegistration",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.AuthApproveRegistrationResponse,
            session=session,
            **kwargs,
        )

    async def Authorize(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.AuthAuthorizePayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _frey_pb2.AuthAuthorizeResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Frey/Authorize",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.AuthAuthorizeResponse,
            session=session,
            **kwargs,
        )

    async def QuickAuthorize(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.AuthQuickAuthorizePayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _frey_pb2.AuthQuickAuthorizeResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Frey/QuickAuthorize",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.AuthQuickAuthorizeResponse,
            session=session,
            **kwargs,
        )

    async def Me(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.AuthMePayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _frey_pb2.AuthMeResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Frey/Me",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.AuthMeResponse,
            session=session,
            **kwargs,
        )

    async def DepersonalizeAccount(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.DepersonalizePayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Frey/DepersonalizeAccount",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def ChangePassword(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.AuthChangePasswordPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _frey_pb2.AuthChangePasswordResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Frey/ChangePassword",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.AuthChangePasswordResponse,
            session=session,
            **kwargs,
        )

    async def RequestResetPassword(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.AuthRequestResetPasswordPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _frey_pb2.AuthRequestResetPasswordResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Frey/RequestResetPassword",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.AuthRequestResetPasswordResponse,
            session=session,
            **kwargs,
        )

    async def ApproveResetPassword(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.AuthApproveResetPasswordPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _frey_pb2.AuthApproveResetPasswordResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Frey/ApproveResetPassword",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.AuthApproveResetPasswordResponse,
            session=session,
            **kwargs,
        )

    async def UpdatePersonalInfo(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.PersonsUpdatePersonalInfoPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Frey/UpdatePersonalInfo",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def GetPersonalInfo(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.PersonsGetPersonalInfoPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _frey_pb2.PersonsGetPersonalInfoResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Frey/GetPersonalInfo",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.PersonsGetPersonalInfoResponse,
            session=session,
            **kwargs,
        )

    async def FindByTenhouIds(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.PersonsFindByTenhouIdsPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _frey_pb2.PersonsFindByTenhouIdsResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Frey/FindByTenhouIds",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.PersonsFindByTenhouIdsResponse,
            session=session,
            **kwargs,
        )

    async def FindByMajsoulAccountId(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.PersonsFindByMajsoulIdsPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _frey_pb2.PersonsFindByTenhouIdsResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Frey/FindByMajsoulAccountId",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.PersonsFindByTenhouIdsResponse,
            session=session,
            **kwargs,
        )

    async def FindByTitle(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.PersonsFindByTitlePayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _frey_pb2.PersonsFindByTitleResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Frey/FindByTitle",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.PersonsFindByTitleResponse,
            session=session,
            **kwargs,
        )

    async def GetEventAdmins(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.AccessGetEventAdminsPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _frey_pb2.AccessGetEventAdminsResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Frey/GetEventAdmins",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.AccessGetEventAdminsResponse,
            session=session,
            **kwargs,
        )

    async def GetEventReferees(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.AccessGetEventRefereesPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _frey_pb2.AccessGetEventRefereesResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Frey/GetEventReferees",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.AccessGetEventRefereesResponse,
            session=session,
            **kwargs,
        )

    async def GetMajsoulNicknames(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.PersonsGetMajsoulNicknamesPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _frey_pb2.PersonsGetMajsoulNicknamesResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Frey/GetMajsoulNicknames",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.PersonsGetMajsoulNicknamesResponse,
            session=session,
            **kwargs,
        )

    async def GetSuperadminFlag(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.AccessGetSuperadminFlagPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _frey_pb2.AccessGetSuperadminFlagResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Frey/GetSuperadminFlag",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.AccessGetSuperadminFlagResponse,
            session=session,
            **kwargs,
        )

    async def GetOwnedEventIds(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.AccessGetOwnedEventIdsPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _frey_pb2.AccessGetOwnedEventIdsResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Frey/GetOwnedEventIds",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.AccessGetOwnedEventIdsResponse,
            session=session,
            **kwargs,
        )

    async def AddRuleForPerson(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.AccessAddRuleForPersonPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _frey_pb2.AccessAddRuleForPersonResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Frey/AddRuleForPerson",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.AccessAddRuleForPersonResponse,
            session=session,
            **kwargs,
        )

    async def DeleteRuleForPerson(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.AccessDeleteRuleForPersonPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Frey/DeleteRuleForPerson",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def CreateAccount(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.PersonsCreateAccountPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _frey_pb2.PersonsCreateAccountResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Frey/CreateAccount",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.PersonsCreateAccountResponse,
            session=session,
            **kwargs,
        )

    async def GetNotificationsSettings(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.PersonsGetNotificationsSettingsPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _frey_pb2.PersonsGetNotificationsSettingsResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Frey/GetNotificationsSettings",
            ctx=ctx,
            request=request,
            response_obj=_frey_pb2.PersonsGetNotificationsSettingsResponse,
            session=session,
            **kwargs,
        )

    async def SetNotificationsSettings(
        self,
        *,
        ctx: Context,
        request: _frey_pb2.PersonsSetNotificationsSettingsPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Frey/SetNotificationsSettings",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )
