# Generated by https://github.com/Cryptact/twirpy/tree/main/protoc-gen-twirpy.  DO NOT EDIT!
# source: proto/frey.proto

from typing import Protocol

from twirp.context import Context
from twirp.endpoint import Endpoint
from twirp.server import TwirpServer

from . import atoms_pb2 as _atoms_pb2
from . import frey_pb2 as _frey_pb2


class FreyServiceProtocol(Protocol):
    async def RequestRegistration(
        self, ctx: Context, request: _frey_pb2.AuthRequestRegistrationPayload
    ) -> _frey_pb2.AuthRequestRegistrationResponse: ...
    async def ApproveRegistration(
        self, ctx: Context, request: _frey_pb2.AuthApproveRegistrationPayload
    ) -> _frey_pb2.AuthApproveRegistrationResponse: ...
    async def Authorize(
        self, ctx: Context, request: _frey_pb2.AuthAuthorizePayload
    ) -> _frey_pb2.AuthAuthorizeResponse: ...
    async def QuickAuthorize(
        self, ctx: Context, request: _frey_pb2.AuthQuickAuthorizePayload
    ) -> _frey_pb2.AuthQuickAuthorizeResponse: ...
    async def Me(
        self, ctx: Context, request: _frey_pb2.AuthMePayload
    ) -> _frey_pb2.AuthMeResponse: ...
    async def DepersonalizeAccount(
        self, ctx: Context, request: _frey_pb2.DepersonalizePayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def ChangePassword(
        self, ctx: Context, request: _frey_pb2.AuthChangePasswordPayload
    ) -> _frey_pb2.AuthChangePasswordResponse: ...
    async def RequestResetPassword(
        self, ctx: Context, request: _frey_pb2.AuthRequestResetPasswordPayload
    ) -> _frey_pb2.AuthRequestResetPasswordResponse: ...
    async def ApproveResetPassword(
        self, ctx: Context, request: _frey_pb2.AuthApproveResetPasswordPayload
    ) -> _frey_pb2.AuthApproveResetPasswordResponse: ...
    async def UpdatePersonalInfo(
        self, ctx: Context, request: _frey_pb2.PersonsUpdatePersonalInfoPayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def GetPersonalInfo(
        self, ctx: Context, request: _frey_pb2.PersonsGetPersonalInfoPayload
    ) -> _frey_pb2.PersonsGetPersonalInfoResponse: ...
    async def FindByTenhouIds(
        self, ctx: Context, request: _frey_pb2.PersonsFindByTenhouIdsPayload
    ) -> _frey_pb2.PersonsFindByTenhouIdsResponse: ...
    async def FindByMajsoulAccountId(
        self, ctx: Context, request: _frey_pb2.PersonsFindByMajsoulIdsPayload
    ) -> _frey_pb2.PersonsFindByTenhouIdsResponse: ...
    async def FindByTitle(
        self, ctx: Context, request: _frey_pb2.PersonsFindByTitlePayload
    ) -> _frey_pb2.PersonsFindByTitleResponse: ...
    async def GetEventAdmins(
        self, ctx: Context, request: _frey_pb2.AccessGetEventAdminsPayload
    ) -> _frey_pb2.AccessGetEventAdminsResponse: ...
    async def GetEventReferees(
        self, ctx: Context, request: _frey_pb2.AccessGetEventRefereesPayload
    ) -> _frey_pb2.AccessGetEventRefereesResponse: ...
    async def GetMajsoulNicknames(
        self, ctx: Context, request: _frey_pb2.PersonsGetMajsoulNicknamesPayload
    ) -> _frey_pb2.PersonsGetMajsoulNicknamesResponse: ...
    async def GetSuperadminFlag(
        self, ctx: Context, request: _frey_pb2.AccessGetSuperadminFlagPayload
    ) -> _frey_pb2.AccessGetSuperadminFlagResponse: ...
    async def GetOwnedEventIds(
        self, ctx: Context, request: _frey_pb2.AccessGetOwnedEventIdsPayload
    ) -> _frey_pb2.AccessGetOwnedEventIdsResponse: ...
    async def AddRuleForPerson(
        self, ctx: Context, request: _frey_pb2.AccessAddRuleForPersonPayload
    ) -> _frey_pb2.AccessAddRuleForPersonResponse: ...
    async def DeleteRuleForPerson(
        self, ctx: Context, request: _frey_pb2.AccessDeleteRuleForPersonPayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def CreateAccount(
        self, ctx: Context, request: _frey_pb2.PersonsCreateAccountPayload
    ) -> _frey_pb2.PersonsCreateAccountResponse: ...
    async def GetNotificationsSettings(
        self, ctx: Context, request: _frey_pb2.PersonsGetNotificationsSettingsPayload
    ) -> _frey_pb2.PersonsGetNotificationsSettingsResponse: ...
    async def SetNotificationsSettings(
        self, ctx: Context, request: _frey_pb2.PersonsSetNotificationsSettingsPayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...


class FreyServer(TwirpServer):
    def __init__(self, *, service: FreyServiceProtocol, server_path_prefix: str = "/twirp"):
        super().__init__(service=service)
        self._prefix = f"{server_path_prefix}/common.Frey"
        self._endpoints = {
            "RequestRegistration": Endpoint(
                service_name="Frey",
                name="RequestRegistration",
                function=service.RequestRegistration,
                input=_frey_pb2.AuthRequestRegistrationPayload,
                output=_frey_pb2.AuthRequestRegistrationResponse,
            ),
            "ApproveRegistration": Endpoint(
                service_name="Frey",
                name="ApproveRegistration",
                function=service.ApproveRegistration,
                input=_frey_pb2.AuthApproveRegistrationPayload,
                output=_frey_pb2.AuthApproveRegistrationResponse,
            ),
            "Authorize": Endpoint(
                service_name="Frey",
                name="Authorize",
                function=service.Authorize,
                input=_frey_pb2.AuthAuthorizePayload,
                output=_frey_pb2.AuthAuthorizeResponse,
            ),
            "QuickAuthorize": Endpoint(
                service_name="Frey",
                name="QuickAuthorize",
                function=service.QuickAuthorize,
                input=_frey_pb2.AuthQuickAuthorizePayload,
                output=_frey_pb2.AuthQuickAuthorizeResponse,
            ),
            "Me": Endpoint(
                service_name="Frey",
                name="Me",
                function=service.Me,
                input=_frey_pb2.AuthMePayload,
                output=_frey_pb2.AuthMeResponse,
            ),
            "DepersonalizeAccount": Endpoint(
                service_name="Frey",
                name="DepersonalizeAccount",
                function=service.DepersonalizeAccount,
                input=_frey_pb2.DepersonalizePayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "ChangePassword": Endpoint(
                service_name="Frey",
                name="ChangePassword",
                function=service.ChangePassword,
                input=_frey_pb2.AuthChangePasswordPayload,
                output=_frey_pb2.AuthChangePasswordResponse,
            ),
            "RequestResetPassword": Endpoint(
                service_name="Frey",
                name="RequestResetPassword",
                function=service.RequestResetPassword,
                input=_frey_pb2.AuthRequestResetPasswordPayload,
                output=_frey_pb2.AuthRequestResetPasswordResponse,
            ),
            "ApproveResetPassword": Endpoint(
                service_name="Frey",
                name="ApproveResetPassword",
                function=service.ApproveResetPassword,
                input=_frey_pb2.AuthApproveResetPasswordPayload,
                output=_frey_pb2.AuthApproveResetPasswordResponse,
            ),
            "UpdatePersonalInfo": Endpoint(
                service_name="Frey",
                name="UpdatePersonalInfo",
                function=service.UpdatePersonalInfo,
                input=_frey_pb2.PersonsUpdatePersonalInfoPayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "GetPersonalInfo": Endpoint(
                service_name="Frey",
                name="GetPersonalInfo",
                function=service.GetPersonalInfo,
                input=_frey_pb2.PersonsGetPersonalInfoPayload,
                output=_frey_pb2.PersonsGetPersonalInfoResponse,
            ),
            "FindByTenhouIds": Endpoint(
                service_name="Frey",
                name="FindByTenhouIds",
                function=service.FindByTenhouIds,
                input=_frey_pb2.PersonsFindByTenhouIdsPayload,
                output=_frey_pb2.PersonsFindByTenhouIdsResponse,
            ),
            "FindByMajsoulAccountId": Endpoint(
                service_name="Frey",
                name="FindByMajsoulAccountId",
                function=service.FindByMajsoulAccountId,
                input=_frey_pb2.PersonsFindByMajsoulIdsPayload,
                output=_frey_pb2.PersonsFindByTenhouIdsResponse,
            ),
            "FindByTitle": Endpoint(
                service_name="Frey",
                name="FindByTitle",
                function=service.FindByTitle,
                input=_frey_pb2.PersonsFindByTitlePayload,
                output=_frey_pb2.PersonsFindByTitleResponse,
            ),
            "GetEventAdmins": Endpoint(
                service_name="Frey",
                name="GetEventAdmins",
                function=service.GetEventAdmins,
                input=_frey_pb2.AccessGetEventAdminsPayload,
                output=_frey_pb2.AccessGetEventAdminsResponse,
            ),
            "GetEventReferees": Endpoint(
                service_name="Frey",
                name="GetEventReferees",
                function=service.GetEventReferees,
                input=_frey_pb2.AccessGetEventRefereesPayload,
                output=_frey_pb2.AccessGetEventRefereesResponse,
            ),
            "GetMajsoulNicknames": Endpoint(
                service_name="Frey",
                name="GetMajsoulNicknames",
                function=service.GetMajsoulNicknames,
                input=_frey_pb2.PersonsGetMajsoulNicknamesPayload,
                output=_frey_pb2.PersonsGetMajsoulNicknamesResponse,
            ),
            "GetSuperadminFlag": Endpoint(
                service_name="Frey",
                name="GetSuperadminFlag",
                function=service.GetSuperadminFlag,
                input=_frey_pb2.AccessGetSuperadminFlagPayload,
                output=_frey_pb2.AccessGetSuperadminFlagResponse,
            ),
            "GetOwnedEventIds": Endpoint(
                service_name="Frey",
                name="GetOwnedEventIds",
                function=service.GetOwnedEventIds,
                input=_frey_pb2.AccessGetOwnedEventIdsPayload,
                output=_frey_pb2.AccessGetOwnedEventIdsResponse,
            ),
            "AddRuleForPerson": Endpoint(
                service_name="Frey",
                name="AddRuleForPerson",
                function=service.AddRuleForPerson,
                input=_frey_pb2.AccessAddRuleForPersonPayload,
                output=_frey_pb2.AccessAddRuleForPersonResponse,
            ),
            "DeleteRuleForPerson": Endpoint(
                service_name="Frey",
                name="DeleteRuleForPerson",
                function=service.DeleteRuleForPerson,
                input=_frey_pb2.AccessDeleteRuleForPersonPayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "CreateAccount": Endpoint(
                service_name="Frey",
                name="CreateAccount",
                function=service.CreateAccount,
                input=_frey_pb2.PersonsCreateAccountPayload,
                output=_frey_pb2.PersonsCreateAccountResponse,
            ),
            "GetNotificationsSettings": Endpoint(
                service_name="Frey",
                name="GetNotificationsSettings",
                function=service.GetNotificationsSettings,
                input=_frey_pb2.PersonsGetNotificationsSettingsPayload,
                output=_frey_pb2.PersonsGetNotificationsSettingsResponse,
            ),
            "SetNotificationsSettings": Endpoint(
                service_name="Frey",
                name="SetNotificationsSettings",
                function=service.SetNotificationsSettings,
                input=_frey_pb2.PersonsSetNotificationsSettingsPayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
        }
