# Generated by https://github.com/Cryptact/twirpy/tree/main/protoc-gen-twirpy.  DO NOT EDIT!
# source: proto/mimir.proto

from typing import Any

from aiohttp import ClientSession
from twirp.async_client import AsyncTwirpClient
from twirp.context import Context

from . import atoms_pb2 as _atoms_pb2
from . import mimir_pb2 as _mimir_pb2


class AsyncMimirClient(AsyncTwirpClient):
    async def GetRulesets(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.EventsGetRulesetsPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _mimir_pb2.EventsGetRulesetsResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetRulesets",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.EventsGetRulesetsResponse,
            session=session,
            **kwargs,
        )

    async def GetEvents(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.EventsGetEventsPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _mimir_pb2.EventsGetEventsResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetEvents",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.EventsGetEventsResponse,
            session=session,
            **kwargs,
        )

    async def GetEventsById(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.EventsGetEventsByIdPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _mimir_pb2.EventsGetEventsByIdResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetEventsById",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.EventsGetEventsByIdResponse,
            session=session,
            **kwargs,
        )

    async def GetMyEvents(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.PlayersGetMyEventsPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _mimir_pb2.PlayersGetMyEventsResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetMyEvents",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.PlayersGetMyEventsResponse,
            session=session,
            **kwargs,
        )

    async def GetGameConfig(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GameConfig:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetGameConfig",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GameConfig,
            session=session,
            **kwargs,
        )

    async def GetRatingTable(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.EventsGetRatingTablePayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _mimir_pb2.EventsGetRatingTableResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetRatingTable",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.EventsGetRatingTableResponse,
            session=session,
            **kwargs,
        )

    async def GetLastGames(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.EventsGetLastGamesPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _mimir_pb2.EventsGetLastGamesResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetLastGames",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.EventsGetLastGamesResponse,
            session=session,
            **kwargs,
        )

    async def GetGame(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericSessionPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _mimir_pb2.EventsGetGameResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetGame",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.EventsGetGameResponse,
            session=session,
            **kwargs,
        )

    async def GetGamesSeries(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _mimir_pb2.EventsGetGamesSeriesResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetGamesSeries",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.EventsGetGamesSeriesResponse,
            session=session,
            **kwargs,
        )

    async def GetCurrentSessions(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.PlayersGetCurrentSessionsPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _mimir_pb2.PlayersGetCurrentSessionsResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetCurrentSessions",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.PlayersGetCurrentSessionsResponse,
            session=session,
            **kwargs,
        )

    async def GetAllRegisteredPlayers(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.EventsGetAllRegisteredPlayersPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _mimir_pb2.EventsGetAllRegisteredPlayersResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetAllRegisteredPlayers",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.EventsGetAllRegisteredPlayersResponse,
            session=session,
            **kwargs,
        )

    async def GetTimerState(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _mimir_pb2.EventsGetTimerStateResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetTimerState",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.EventsGetTimerStateResponse,
            session=session,
            **kwargs,
        )

    async def GetSessionOverview(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericSessionPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _mimir_pb2.GamesGetSessionOverviewResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetSessionOverview",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.GamesGetSessionOverviewResponse,
            session=session,
            **kwargs,
        )

    async def GetPlayerStats(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.PlayersGetPlayerStatsPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _mimir_pb2.PlayersGetPlayerStatsResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetPlayerStats",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.PlayersGetPlayerStatsResponse,
            session=session,
            **kwargs,
        )

    async def AddRound(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.GamesAddRoundPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _mimir_pb2.GamesAddRoundResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/AddRound",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.GamesAddRoundResponse,
            session=session,
            **kwargs,
        )

    async def PreviewRound(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.GamesPreviewRoundPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _mimir_pb2.GamesPreviewRoundResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/PreviewRound",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.GamesPreviewRoundResponse,
            session=session,
            **kwargs,
        )

    async def AddOnlineReplay(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.GamesAddOnlineReplayPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _mimir_pb2.GamesAddOnlineReplayResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/AddOnlineReplay",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.GamesAddOnlineReplayResponse,
            session=session,
            **kwargs,
        )

    async def GetLastResults(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.PlayersGetLastResultsPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _mimir_pb2.PlayersGetLastResultsResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetLastResults",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.PlayersGetLastResultsResponse,
            session=session,
            **kwargs,
        )

    async def GetLastRound(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.PlayersGetLastRoundPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _mimir_pb2.PlayersGetLastRoundResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetLastRound",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.PlayersGetLastRoundResponse,
            session=session,
            **kwargs,
        )

    async def GetAllRounds(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericSessionPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _mimir_pb2.PlayersGetAllRoundsResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetAllRounds",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.PlayersGetAllRoundsResponse,
            session=session,
            **kwargs,
        )

    async def GetLastRoundByHash(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericSessionPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _mimir_pb2.PlayersGetLastRoundByHashResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetLastRoundByHash",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.PlayersGetLastRoundByHashResponse,
            session=session,
            **kwargs,
        )

    async def GetEventForEdit(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.EventsGetEventForEditPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _mimir_pb2.EventsGetEventForEditResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetEventForEdit",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.EventsGetEventForEditResponse,
            session=session,
            **kwargs,
        )

    async def RebuildScoring(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/RebuildScoring",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def CreateEvent(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.EventData,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericEventPayload:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/CreateEvent",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericEventPayload,
            session=session,
            **kwargs,
        )

    async def UpdateEvent(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.EventsUpdateEventPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/UpdateEvent",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def FinishEvent(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/FinishEvent",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def ToggleListed(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/ToggleListed",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def GetTablesState(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.EventsGetTablesStatePayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _mimir_pb2.EventsGetTablesStateResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetTablesState",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.EventsGetTablesStateResponse,
            session=session,
            **kwargs,
        )

    async def StartTimer(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/StartTimer",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def RegisterPlayer(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.EventsRegisterPlayerPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/RegisterPlayer",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def UnregisterPlayer(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.EventsUnregisterPlayerPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/UnregisterPlayer",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def UpdatePlayerSeatingFlag(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.EventsUpdatePlayerSeatingFlagPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/UpdatePlayerSeatingFlag",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def GetAchievements(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.EventsGetAchievementsPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _mimir_pb2.EventsGetAchievementsResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetAchievements",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.EventsGetAchievementsResponse,
            session=session,
            **kwargs,
        )

    async def ToggleHideResults(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/ToggleHideResults",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def ToggleHideAchievements(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/ToggleHideAchievements",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def UpdatePlayersLocalIds(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.EventsUpdatePlayersLocalIdsPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/UpdatePlayersLocalIds",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def UpdatePlayerReplacement(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.EventsUpdatePlayerReplacementPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/UpdatePlayerReplacement",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def UpdatePlayersTeams(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.EventsUpdatePlayersTeamsPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/UpdatePlayersTeams",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def StartGame(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.GamesStartGamePayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSessionPayload:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/StartGame",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSessionPayload,
            session=session,
            **kwargs,
        )

    async def EndGame(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericSessionPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/EndGame",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def CancelGame(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericSessionPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/CancelGame",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def FinalizeSession(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/FinalizeSession",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def DropLastRound(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.GamesDropLastRoundPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/DropLastRound",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def DefinalizeGame(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericSessionPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/DefinalizeGame",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def AddPenalty(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.GamesAddPenaltyPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/AddPenalty",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def AddPenaltyGame(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.GamesAddPenaltyGamePayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSessionPayload:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/AddPenaltyGame",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSessionPayload,
            session=session,
            **kwargs,
        )

    async def GetPlayer(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.PlayersGetPlayerPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _mimir_pb2.PlayersGetPlayerResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetPlayer",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.PlayersGetPlayerResponse,
            session=session,
            **kwargs,
        )

    async def GetCurrentSeating(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _mimir_pb2.EventsGetCurrentSeatingResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetCurrentSeating",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.EventsGetCurrentSeatingResponse,
            session=session,
            **kwargs,
        )

    async def MakeShuffledSeating(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.SeatingMakeShuffledSeatingPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/MakeShuffledSeating",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def MakeSwissSeating(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/MakeSwissSeating",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def ResetSeating(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/ResetSeating",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def GenerateSwissSeating(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.SeatingGenerateSwissSeatingPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _mimir_pb2.SeatingGenerateSwissSeatingResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GenerateSwissSeating",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.SeatingGenerateSwissSeatingResponse,
            session=session,
            **kwargs,
        )

    async def MakeIntervalSeating(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.SeatingMakeIntervalSeatingPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/MakeIntervalSeating",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def MakePrescriptedSeating(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.SeatingMakePrescriptedSeatingPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/MakePrescriptedSeating",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def GetNextPrescriptedSeating(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _mimir_pb2.SeatingGetNextPrescriptedSeatingResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetNextPrescriptedSeating",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.SeatingGetNextPrescriptedSeatingResponse,
            session=session,
            **kwargs,
        )

    async def GetPrescriptedEventConfig(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _mimir_pb2.EventsGetPrescriptedEventConfigResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetPrescriptedEventConfig",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.EventsGetPrescriptedEventConfigResponse,
            session=session,
            **kwargs,
        )

    async def UpdatePrescriptedEventConfig(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.EventsUpdatePrescriptedEventConfigPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/UpdatePrescriptedEventConfig",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def InitStartingTimer(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/InitStartingTimer",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def GetStartingTimer(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _mimir_pb2.EventsGetStartingTimerResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetStartingTimer",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.EventsGetStartingTimerResponse,
            session=session,
            **kwargs,
        )

    async def ClearStatCache(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.ClearStatCachePayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/ClearStatCache",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def ForceFinishGame(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericSessionPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/ForceFinishGame",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def AddTypedOnlineReplay(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.TypedGamesAddOnlineReplayPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _mimir_pb2.GamesAddOnlineReplayResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/AddTypedOnlineReplay",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.GamesAddOnlineReplayResponse,
            session=session,
            **kwargs,
        )

    async def NotifyPlayersSessionStartsSoon(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/NotifyPlayersSessionStartsSoon",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def CallReferee(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.CallRefereePayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/CallReferee",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def RecalcAchievements(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/RecalcAchievements",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def RecalcPlayerStats(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/RecalcPlayerStats",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def ListPenalties(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _mimir_pb2.PenaltiesResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/ListPenalties",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.PenaltiesResponse,
            session=session,
            **kwargs,
        )

    async def CancelPenalty(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.CancelPenaltyPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/CancelPenalty",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def AddExtraTime(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.AddExtraTimePayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/AddExtraTime",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            session=session,
            **kwargs,
        )

    async def ListMyPenalties(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _mimir_pb2.PenaltiesResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/ListMyPenalties",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.PenaltiesResponse,
            session=session,
            **kwargs,
        )

    async def ListChombo(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _mimir_pb2.ChomboResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/ListChombo",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.ChomboResponse,
            session=session,
            **kwargs,
        )

    async def GetCurrentStateForPlayer(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.GetCurrentStatePayload,
        server_path_prefix: str = "/twirp",
        session: ClientSession | None = None,
        **kwargs: Any,
    ) -> _mimir_pb2.GetCurrentStateResponse:
        return await self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetCurrentStateForPlayer",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.GetCurrentStateResponse,
            session=session,
            **kwargs,
        )
