# Generated by https://github.com/Cryptact/twirpy/tree/main/protoc-gen-twirpy.  DO NOT EDIT!
# source: proto/mimir.proto

from typing import Protocol

from twirp.context import Context
from twirp.endpoint import Endpoint
from twirp.server import TwirpServer

from . import atoms_pb2 as _atoms_pb2
from . import mimir_pb2 as _mimir_pb2


class MimirServiceProtocol(Protocol):
    async def GetRulesets(
        self, ctx: Context, request: _mimir_pb2.EventsGetRulesetsPayload
    ) -> _mimir_pb2.EventsGetRulesetsResponse: ...
    async def GetEvents(
        self, ctx: Context, request: _mimir_pb2.EventsGetEventsPayload
    ) -> _mimir_pb2.EventsGetEventsResponse: ...
    async def GetEventsById(
        self, ctx: Context, request: _mimir_pb2.EventsGetEventsByIdPayload
    ) -> _mimir_pb2.EventsGetEventsByIdResponse: ...
    async def GetMyEvents(
        self, ctx: Context, request: _mimir_pb2.PlayersGetMyEventsPayload
    ) -> _mimir_pb2.PlayersGetMyEventsResponse: ...
    async def GetGameConfig(
        self, ctx: Context, request: _atoms_pb2.GenericEventPayload
    ) -> _atoms_pb2.GameConfig: ...
    async def GetRatingTable(
        self, ctx: Context, request: _mimir_pb2.EventsGetRatingTablePayload
    ) -> _mimir_pb2.EventsGetRatingTableResponse: ...
    async def GetLastGames(
        self, ctx: Context, request: _mimir_pb2.EventsGetLastGamesPayload
    ) -> _mimir_pb2.EventsGetLastGamesResponse: ...
    async def GetGame(
        self, ctx: Context, request: _atoms_pb2.GenericSessionPayload
    ) -> _mimir_pb2.EventsGetGameResponse: ...
    async def GetGamesSeries(
        self, ctx: Context, request: _atoms_pb2.GenericEventPayload
    ) -> _mimir_pb2.EventsGetGamesSeriesResponse: ...
    async def GetCurrentSessions(
        self, ctx: Context, request: _mimir_pb2.PlayersGetCurrentSessionsPayload
    ) -> _mimir_pb2.PlayersGetCurrentSessionsResponse: ...
    async def GetAllRegisteredPlayers(
        self, ctx: Context, request: _mimir_pb2.EventsGetAllRegisteredPlayersPayload
    ) -> _mimir_pb2.EventsGetAllRegisteredPlayersResponse: ...
    async def GetTimerState(
        self, ctx: Context, request: _atoms_pb2.GenericEventPayload
    ) -> _mimir_pb2.EventsGetTimerStateResponse: ...
    async def GetSessionOverview(
        self, ctx: Context, request: _atoms_pb2.GenericSessionPayload
    ) -> _mimir_pb2.GamesGetSessionOverviewResponse: ...
    async def GetPlayerStats(
        self, ctx: Context, request: _mimir_pb2.PlayersGetPlayerStatsPayload
    ) -> _mimir_pb2.PlayersGetPlayerStatsResponse: ...
    async def AddRound(
        self, ctx: Context, request: _mimir_pb2.GamesAddRoundPayload
    ) -> _mimir_pb2.GamesAddRoundResponse: ...
    async def PreviewRound(
        self, ctx: Context, request: _mimir_pb2.GamesPreviewRoundPayload
    ) -> _mimir_pb2.GamesPreviewRoundResponse: ...
    async def AddOnlineReplay(
        self, ctx: Context, request: _mimir_pb2.GamesAddOnlineReplayPayload
    ) -> _mimir_pb2.GamesAddOnlineReplayResponse: ...
    async def GetLastResults(
        self, ctx: Context, request: _mimir_pb2.PlayersGetLastResultsPayload
    ) -> _mimir_pb2.PlayersGetLastResultsResponse: ...
    async def GetLastRound(
        self, ctx: Context, request: _mimir_pb2.PlayersGetLastRoundPayload
    ) -> _mimir_pb2.PlayersGetLastRoundResponse: ...
    async def GetAllRounds(
        self, ctx: Context, request: _atoms_pb2.GenericSessionPayload
    ) -> _mimir_pb2.PlayersGetAllRoundsResponse: ...
    async def GetLastRoundByHash(
        self, ctx: Context, request: _atoms_pb2.GenericSessionPayload
    ) -> _mimir_pb2.PlayersGetLastRoundByHashResponse: ...
    async def GetEventForEdit(
        self, ctx: Context, request: _mimir_pb2.EventsGetEventForEditPayload
    ) -> _mimir_pb2.EventsGetEventForEditResponse: ...
    async def RebuildScoring(
        self, ctx: Context, request: _atoms_pb2.GenericEventPayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def CreateEvent(
        self, ctx: Context, request: _atoms_pb2.EventData
    ) -> _atoms_pb2.GenericEventPayload: ...
    async def UpdateEvent(
        self, ctx: Context, request: _mimir_pb2.EventsUpdateEventPayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def FinishEvent(
        self, ctx: Context, request: _atoms_pb2.GenericEventPayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def ToggleListed(
        self, ctx: Context, request: _atoms_pb2.GenericEventPayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def GetTablesState(
        self, ctx: Context, request: _mimir_pb2.EventsGetTablesStatePayload
    ) -> _mimir_pb2.EventsGetTablesStateResponse: ...
    async def StartTimer(
        self, ctx: Context, request: _atoms_pb2.GenericEventPayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def RegisterPlayer(
        self, ctx: Context, request: _mimir_pb2.EventsRegisterPlayerPayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def UnregisterPlayer(
        self, ctx: Context, request: _mimir_pb2.EventsUnregisterPlayerPayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def UpdatePlayerSeatingFlag(
        self, ctx: Context, request: _mimir_pb2.EventsUpdatePlayerSeatingFlagPayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def GetAchievements(
        self, ctx: Context, request: _mimir_pb2.EventsGetAchievementsPayload
    ) -> _mimir_pb2.EventsGetAchievementsResponse: ...
    async def ToggleHideResults(
        self, ctx: Context, request: _atoms_pb2.GenericEventPayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def ToggleHideAchievements(
        self, ctx: Context, request: _atoms_pb2.GenericEventPayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def UpdatePlayersLocalIds(
        self, ctx: Context, request: _mimir_pb2.EventsUpdatePlayersLocalIdsPayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def UpdatePlayerReplacement(
        self, ctx: Context, request: _mimir_pb2.EventsUpdatePlayerReplacementPayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def UpdatePlayersTeams(
        self, ctx: Context, request: _mimir_pb2.EventsUpdatePlayersTeamsPayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def StartGame(
        self, ctx: Context, request: _mimir_pb2.GamesStartGamePayload
    ) -> _atoms_pb2.GenericSessionPayload: ...
    async def EndGame(
        self, ctx: Context, request: _atoms_pb2.GenericSessionPayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def CancelGame(
        self, ctx: Context, request: _atoms_pb2.GenericSessionPayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def FinalizeSession(
        self, ctx: Context, request: _atoms_pb2.GenericEventPayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def DropLastRound(
        self, ctx: Context, request: _mimir_pb2.GamesDropLastRoundPayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def DefinalizeGame(
        self, ctx: Context, request: _atoms_pb2.GenericSessionPayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def AddPenalty(
        self, ctx: Context, request: _mimir_pb2.GamesAddPenaltyPayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def AddPenaltyGame(
        self, ctx: Context, request: _mimir_pb2.GamesAddPenaltyGamePayload
    ) -> _atoms_pb2.GenericSessionPayload: ...
    async def GetPlayer(
        self, ctx: Context, request: _mimir_pb2.PlayersGetPlayerPayload
    ) -> _mimir_pb2.PlayersGetPlayerResponse: ...
    async def GetCurrentSeating(
        self, ctx: Context, request: _atoms_pb2.GenericEventPayload
    ) -> _mimir_pb2.EventsGetCurrentSeatingResponse: ...
    async def MakeShuffledSeating(
        self, ctx: Context, request: _mimir_pb2.SeatingMakeShuffledSeatingPayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def MakeSwissSeating(
        self, ctx: Context, request: _atoms_pb2.GenericEventPayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def ResetSeating(
        self, ctx: Context, request: _atoms_pb2.GenericEventPayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def GenerateSwissSeating(
        self, ctx: Context, request: _mimir_pb2.SeatingGenerateSwissSeatingPayload
    ) -> _mimir_pb2.SeatingGenerateSwissSeatingResponse: ...
    async def MakeIntervalSeating(
        self, ctx: Context, request: _mimir_pb2.SeatingMakeIntervalSeatingPayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def MakePrescriptedSeating(
        self, ctx: Context, request: _mimir_pb2.SeatingMakePrescriptedSeatingPayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def GetNextPrescriptedSeating(
        self, ctx: Context, request: _atoms_pb2.GenericEventPayload
    ) -> _mimir_pb2.SeatingGetNextPrescriptedSeatingResponse: ...
    async def GetPrescriptedEventConfig(
        self, ctx: Context, request: _atoms_pb2.GenericEventPayload
    ) -> _mimir_pb2.EventsGetPrescriptedEventConfigResponse: ...
    async def UpdatePrescriptedEventConfig(
        self, ctx: Context, request: _mimir_pb2.EventsUpdatePrescriptedEventConfigPayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def InitStartingTimer(
        self, ctx: Context, request: _atoms_pb2.GenericEventPayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def GetStartingTimer(
        self, ctx: Context, request: _atoms_pb2.GenericEventPayload
    ) -> _mimir_pb2.EventsGetStartingTimerResponse: ...
    async def ClearStatCache(
        self, ctx: Context, request: _mimir_pb2.ClearStatCachePayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def ForceFinishGame(
        self, ctx: Context, request: _atoms_pb2.GenericSessionPayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def AddTypedOnlineReplay(
        self, ctx: Context, request: _mimir_pb2.TypedGamesAddOnlineReplayPayload
    ) -> _mimir_pb2.GamesAddOnlineReplayResponse: ...
    async def NotifyPlayersSessionStartsSoon(
        self, ctx: Context, request: _atoms_pb2.GenericEventPayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def CallReferee(
        self, ctx: Context, request: _mimir_pb2.CallRefereePayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def RecalcAchievements(
        self, ctx: Context, request: _atoms_pb2.GenericEventPayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def RecalcPlayerStats(
        self, ctx: Context, request: _atoms_pb2.GenericEventPayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def ListPenalties(
        self, ctx: Context, request: _atoms_pb2.GenericEventPayload
    ) -> _mimir_pb2.PenaltiesResponse: ...
    async def CancelPenalty(
        self, ctx: Context, request: _mimir_pb2.CancelPenaltyPayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def AddExtraTime(
        self, ctx: Context, request: _mimir_pb2.AddExtraTimePayload
    ) -> _atoms_pb2.GenericSuccessResponse: ...
    async def ListMyPenalties(
        self, ctx: Context, request: _atoms_pb2.GenericEventPayload
    ) -> _mimir_pb2.PenaltiesResponse: ...
    async def ListChombo(
        self, ctx: Context, request: _atoms_pb2.GenericEventPayload
    ) -> _mimir_pb2.ChomboResponse: ...
    async def GetCurrentStateForPlayer(
        self, ctx: Context, request: _mimir_pb2.GetCurrentStatePayload
    ) -> _mimir_pb2.GetCurrentStateResponse: ...


class MimirServer(TwirpServer):
    def __init__(self, *, service: MimirServiceProtocol, server_path_prefix: str = "/twirp"):
        super().__init__(service=service)
        self._prefix = f"{server_path_prefix}/common.Mimir"
        self._endpoints = {
            "GetRulesets": Endpoint(
                service_name="Mimir",
                name="GetRulesets",
                function=service.GetRulesets,
                input=_mimir_pb2.EventsGetRulesetsPayload,
                output=_mimir_pb2.EventsGetRulesetsResponse,
            ),
            "GetEvents": Endpoint(
                service_name="Mimir",
                name="GetEvents",
                function=service.GetEvents,
                input=_mimir_pb2.EventsGetEventsPayload,
                output=_mimir_pb2.EventsGetEventsResponse,
            ),
            "GetEventsById": Endpoint(
                service_name="Mimir",
                name="GetEventsById",
                function=service.GetEventsById,
                input=_mimir_pb2.EventsGetEventsByIdPayload,
                output=_mimir_pb2.EventsGetEventsByIdResponse,
            ),
            "GetMyEvents": Endpoint(
                service_name="Mimir",
                name="GetMyEvents",
                function=service.GetMyEvents,
                input=_mimir_pb2.PlayersGetMyEventsPayload,
                output=_mimir_pb2.PlayersGetMyEventsResponse,
            ),
            "GetGameConfig": Endpoint(
                service_name="Mimir",
                name="GetGameConfig",
                function=service.GetGameConfig,
                input=_atoms_pb2.GenericEventPayload,
                output=_atoms_pb2.GameConfig,
            ),
            "GetRatingTable": Endpoint(
                service_name="Mimir",
                name="GetRatingTable",
                function=service.GetRatingTable,
                input=_mimir_pb2.EventsGetRatingTablePayload,
                output=_mimir_pb2.EventsGetRatingTableResponse,
            ),
            "GetLastGames": Endpoint(
                service_name="Mimir",
                name="GetLastGames",
                function=service.GetLastGames,
                input=_mimir_pb2.EventsGetLastGamesPayload,
                output=_mimir_pb2.EventsGetLastGamesResponse,
            ),
            "GetGame": Endpoint(
                service_name="Mimir",
                name="GetGame",
                function=service.GetGame,
                input=_atoms_pb2.GenericSessionPayload,
                output=_mimir_pb2.EventsGetGameResponse,
            ),
            "GetGamesSeries": Endpoint(
                service_name="Mimir",
                name="GetGamesSeries",
                function=service.GetGamesSeries,
                input=_atoms_pb2.GenericEventPayload,
                output=_mimir_pb2.EventsGetGamesSeriesResponse,
            ),
            "GetCurrentSessions": Endpoint(
                service_name="Mimir",
                name="GetCurrentSessions",
                function=service.GetCurrentSessions,
                input=_mimir_pb2.PlayersGetCurrentSessionsPayload,
                output=_mimir_pb2.PlayersGetCurrentSessionsResponse,
            ),
            "GetAllRegisteredPlayers": Endpoint(
                service_name="Mimir",
                name="GetAllRegisteredPlayers",
                function=service.GetAllRegisteredPlayers,
                input=_mimir_pb2.EventsGetAllRegisteredPlayersPayload,
                output=_mimir_pb2.EventsGetAllRegisteredPlayersResponse,
            ),
            "GetTimerState": Endpoint(
                service_name="Mimir",
                name="GetTimerState",
                function=service.GetTimerState,
                input=_atoms_pb2.GenericEventPayload,
                output=_mimir_pb2.EventsGetTimerStateResponse,
            ),
            "GetSessionOverview": Endpoint(
                service_name="Mimir",
                name="GetSessionOverview",
                function=service.GetSessionOverview,
                input=_atoms_pb2.GenericSessionPayload,
                output=_mimir_pb2.GamesGetSessionOverviewResponse,
            ),
            "GetPlayerStats": Endpoint(
                service_name="Mimir",
                name="GetPlayerStats",
                function=service.GetPlayerStats,
                input=_mimir_pb2.PlayersGetPlayerStatsPayload,
                output=_mimir_pb2.PlayersGetPlayerStatsResponse,
            ),
            "AddRound": Endpoint(
                service_name="Mimir",
                name="AddRound",
                function=service.AddRound,
                input=_mimir_pb2.GamesAddRoundPayload,
                output=_mimir_pb2.GamesAddRoundResponse,
            ),
            "PreviewRound": Endpoint(
                service_name="Mimir",
                name="PreviewRound",
                function=service.PreviewRound,
                input=_mimir_pb2.GamesPreviewRoundPayload,
                output=_mimir_pb2.GamesPreviewRoundResponse,
            ),
            "AddOnlineReplay": Endpoint(
                service_name="Mimir",
                name="AddOnlineReplay",
                function=service.AddOnlineReplay,
                input=_mimir_pb2.GamesAddOnlineReplayPayload,
                output=_mimir_pb2.GamesAddOnlineReplayResponse,
            ),
            "GetLastResults": Endpoint(
                service_name="Mimir",
                name="GetLastResults",
                function=service.GetLastResults,
                input=_mimir_pb2.PlayersGetLastResultsPayload,
                output=_mimir_pb2.PlayersGetLastResultsResponse,
            ),
            "GetLastRound": Endpoint(
                service_name="Mimir",
                name="GetLastRound",
                function=service.GetLastRound,
                input=_mimir_pb2.PlayersGetLastRoundPayload,
                output=_mimir_pb2.PlayersGetLastRoundResponse,
            ),
            "GetAllRounds": Endpoint(
                service_name="Mimir",
                name="GetAllRounds",
                function=service.GetAllRounds,
                input=_atoms_pb2.GenericSessionPayload,
                output=_mimir_pb2.PlayersGetAllRoundsResponse,
            ),
            "GetLastRoundByHash": Endpoint(
                service_name="Mimir",
                name="GetLastRoundByHash",
                function=service.GetLastRoundByHash,
                input=_atoms_pb2.GenericSessionPayload,
                output=_mimir_pb2.PlayersGetLastRoundByHashResponse,
            ),
            "GetEventForEdit": Endpoint(
                service_name="Mimir",
                name="GetEventForEdit",
                function=service.GetEventForEdit,
                input=_mimir_pb2.EventsGetEventForEditPayload,
                output=_mimir_pb2.EventsGetEventForEditResponse,
            ),
            "RebuildScoring": Endpoint(
                service_name="Mimir",
                name="RebuildScoring",
                function=service.RebuildScoring,
                input=_atoms_pb2.GenericEventPayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "CreateEvent": Endpoint(
                service_name="Mimir",
                name="CreateEvent",
                function=service.CreateEvent,
                input=_atoms_pb2.EventData,
                output=_atoms_pb2.GenericEventPayload,
            ),
            "UpdateEvent": Endpoint(
                service_name="Mimir",
                name="UpdateEvent",
                function=service.UpdateEvent,
                input=_mimir_pb2.EventsUpdateEventPayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "FinishEvent": Endpoint(
                service_name="Mimir",
                name="FinishEvent",
                function=service.FinishEvent,
                input=_atoms_pb2.GenericEventPayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "ToggleListed": Endpoint(
                service_name="Mimir",
                name="ToggleListed",
                function=service.ToggleListed,
                input=_atoms_pb2.GenericEventPayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "GetTablesState": Endpoint(
                service_name="Mimir",
                name="GetTablesState",
                function=service.GetTablesState,
                input=_mimir_pb2.EventsGetTablesStatePayload,
                output=_mimir_pb2.EventsGetTablesStateResponse,
            ),
            "StartTimer": Endpoint(
                service_name="Mimir",
                name="StartTimer",
                function=service.StartTimer,
                input=_atoms_pb2.GenericEventPayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "RegisterPlayer": Endpoint(
                service_name="Mimir",
                name="RegisterPlayer",
                function=service.RegisterPlayer,
                input=_mimir_pb2.EventsRegisterPlayerPayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "UnregisterPlayer": Endpoint(
                service_name="Mimir",
                name="UnregisterPlayer",
                function=service.UnregisterPlayer,
                input=_mimir_pb2.EventsUnregisterPlayerPayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "UpdatePlayerSeatingFlag": Endpoint(
                service_name="Mimir",
                name="UpdatePlayerSeatingFlag",
                function=service.UpdatePlayerSeatingFlag,
                input=_mimir_pb2.EventsUpdatePlayerSeatingFlagPayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "GetAchievements": Endpoint(
                service_name="Mimir",
                name="GetAchievements",
                function=service.GetAchievements,
                input=_mimir_pb2.EventsGetAchievementsPayload,
                output=_mimir_pb2.EventsGetAchievementsResponse,
            ),
            "ToggleHideResults": Endpoint(
                service_name="Mimir",
                name="ToggleHideResults",
                function=service.ToggleHideResults,
                input=_atoms_pb2.GenericEventPayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "ToggleHideAchievements": Endpoint(
                service_name="Mimir",
                name="ToggleHideAchievements",
                function=service.ToggleHideAchievements,
                input=_atoms_pb2.GenericEventPayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "UpdatePlayersLocalIds": Endpoint(
                service_name="Mimir",
                name="UpdatePlayersLocalIds",
                function=service.UpdatePlayersLocalIds,
                input=_mimir_pb2.EventsUpdatePlayersLocalIdsPayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "UpdatePlayerReplacement": Endpoint(
                service_name="Mimir",
                name="UpdatePlayerReplacement",
                function=service.UpdatePlayerReplacement,
                input=_mimir_pb2.EventsUpdatePlayerReplacementPayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "UpdatePlayersTeams": Endpoint(
                service_name="Mimir",
                name="UpdatePlayersTeams",
                function=service.UpdatePlayersTeams,
                input=_mimir_pb2.EventsUpdatePlayersTeamsPayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "StartGame": Endpoint(
                service_name="Mimir",
                name="StartGame",
                function=service.StartGame,
                input=_mimir_pb2.GamesStartGamePayload,
                output=_atoms_pb2.GenericSessionPayload,
            ),
            "EndGame": Endpoint(
                service_name="Mimir",
                name="EndGame",
                function=service.EndGame,
                input=_atoms_pb2.GenericSessionPayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "CancelGame": Endpoint(
                service_name="Mimir",
                name="CancelGame",
                function=service.CancelGame,
                input=_atoms_pb2.GenericSessionPayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "FinalizeSession": Endpoint(
                service_name="Mimir",
                name="FinalizeSession",
                function=service.FinalizeSession,
                input=_atoms_pb2.GenericEventPayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "DropLastRound": Endpoint(
                service_name="Mimir",
                name="DropLastRound",
                function=service.DropLastRound,
                input=_mimir_pb2.GamesDropLastRoundPayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "DefinalizeGame": Endpoint(
                service_name="Mimir",
                name="DefinalizeGame",
                function=service.DefinalizeGame,
                input=_atoms_pb2.GenericSessionPayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "AddPenalty": Endpoint(
                service_name="Mimir",
                name="AddPenalty",
                function=service.AddPenalty,
                input=_mimir_pb2.GamesAddPenaltyPayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "AddPenaltyGame": Endpoint(
                service_name="Mimir",
                name="AddPenaltyGame",
                function=service.AddPenaltyGame,
                input=_mimir_pb2.GamesAddPenaltyGamePayload,
                output=_atoms_pb2.GenericSessionPayload,
            ),
            "GetPlayer": Endpoint(
                service_name="Mimir",
                name="GetPlayer",
                function=service.GetPlayer,
                input=_mimir_pb2.PlayersGetPlayerPayload,
                output=_mimir_pb2.PlayersGetPlayerResponse,
            ),
            "GetCurrentSeating": Endpoint(
                service_name="Mimir",
                name="GetCurrentSeating",
                function=service.GetCurrentSeating,
                input=_atoms_pb2.GenericEventPayload,
                output=_mimir_pb2.EventsGetCurrentSeatingResponse,
            ),
            "MakeShuffledSeating": Endpoint(
                service_name="Mimir",
                name="MakeShuffledSeating",
                function=service.MakeShuffledSeating,
                input=_mimir_pb2.SeatingMakeShuffledSeatingPayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "MakeSwissSeating": Endpoint(
                service_name="Mimir",
                name="MakeSwissSeating",
                function=service.MakeSwissSeating,
                input=_atoms_pb2.GenericEventPayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "ResetSeating": Endpoint(
                service_name="Mimir",
                name="ResetSeating",
                function=service.ResetSeating,
                input=_atoms_pb2.GenericEventPayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "GenerateSwissSeating": Endpoint(
                service_name="Mimir",
                name="GenerateSwissSeating",
                function=service.GenerateSwissSeating,
                input=_mimir_pb2.SeatingGenerateSwissSeatingPayload,
                output=_mimir_pb2.SeatingGenerateSwissSeatingResponse,
            ),
            "MakeIntervalSeating": Endpoint(
                service_name="Mimir",
                name="MakeIntervalSeating",
                function=service.MakeIntervalSeating,
                input=_mimir_pb2.SeatingMakeIntervalSeatingPayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "MakePrescriptedSeating": Endpoint(
                service_name="Mimir",
                name="MakePrescriptedSeating",
                function=service.MakePrescriptedSeating,
                input=_mimir_pb2.SeatingMakePrescriptedSeatingPayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "GetNextPrescriptedSeating": Endpoint(
                service_name="Mimir",
                name="GetNextPrescriptedSeating",
                function=service.GetNextPrescriptedSeating,
                input=_atoms_pb2.GenericEventPayload,
                output=_mimir_pb2.SeatingGetNextPrescriptedSeatingResponse,
            ),
            "GetPrescriptedEventConfig": Endpoint(
                service_name="Mimir",
                name="GetPrescriptedEventConfig",
                function=service.GetPrescriptedEventConfig,
                input=_atoms_pb2.GenericEventPayload,
                output=_mimir_pb2.EventsGetPrescriptedEventConfigResponse,
            ),
            "UpdatePrescriptedEventConfig": Endpoint(
                service_name="Mimir",
                name="UpdatePrescriptedEventConfig",
                function=service.UpdatePrescriptedEventConfig,
                input=_mimir_pb2.EventsUpdatePrescriptedEventConfigPayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "InitStartingTimer": Endpoint(
                service_name="Mimir",
                name="InitStartingTimer",
                function=service.InitStartingTimer,
                input=_atoms_pb2.GenericEventPayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "GetStartingTimer": Endpoint(
                service_name="Mimir",
                name="GetStartingTimer",
                function=service.GetStartingTimer,
                input=_atoms_pb2.GenericEventPayload,
                output=_mimir_pb2.EventsGetStartingTimerResponse,
            ),
            "ClearStatCache": Endpoint(
                service_name="Mimir",
                name="ClearStatCache",
                function=service.ClearStatCache,
                input=_mimir_pb2.ClearStatCachePayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "ForceFinishGame": Endpoint(
                service_name="Mimir",
                name="ForceFinishGame",
                function=service.ForceFinishGame,
                input=_atoms_pb2.GenericSessionPayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "AddTypedOnlineReplay": Endpoint(
                service_name="Mimir",
                name="AddTypedOnlineReplay",
                function=service.AddTypedOnlineReplay,
                input=_mimir_pb2.TypedGamesAddOnlineReplayPayload,
                output=_mimir_pb2.GamesAddOnlineReplayResponse,
            ),
            "NotifyPlayersSessionStartsSoon": Endpoint(
                service_name="Mimir",
                name="NotifyPlayersSessionStartsSoon",
                function=service.NotifyPlayersSessionStartsSoon,
                input=_atoms_pb2.GenericEventPayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "CallReferee": Endpoint(
                service_name="Mimir",
                name="CallReferee",
                function=service.CallReferee,
                input=_mimir_pb2.CallRefereePayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "RecalcAchievements": Endpoint(
                service_name="Mimir",
                name="RecalcAchievements",
                function=service.RecalcAchievements,
                input=_atoms_pb2.GenericEventPayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "RecalcPlayerStats": Endpoint(
                service_name="Mimir",
                name="RecalcPlayerStats",
                function=service.RecalcPlayerStats,
                input=_atoms_pb2.GenericEventPayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "ListPenalties": Endpoint(
                service_name="Mimir",
                name="ListPenalties",
                function=service.ListPenalties,
                input=_atoms_pb2.GenericEventPayload,
                output=_mimir_pb2.PenaltiesResponse,
            ),
            "CancelPenalty": Endpoint(
                service_name="Mimir",
                name="CancelPenalty",
                function=service.CancelPenalty,
                input=_mimir_pb2.CancelPenaltyPayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "AddExtraTime": Endpoint(
                service_name="Mimir",
                name="AddExtraTime",
                function=service.AddExtraTime,
                input=_mimir_pb2.AddExtraTimePayload,
                output=_atoms_pb2.GenericSuccessResponse,
            ),
            "ListMyPenalties": Endpoint(
                service_name="Mimir",
                name="ListMyPenalties",
                function=service.ListMyPenalties,
                input=_atoms_pb2.GenericEventPayload,
                output=_mimir_pb2.PenaltiesResponse,
            ),
            "ListChombo": Endpoint(
                service_name="Mimir",
                name="ListChombo",
                function=service.ListChombo,
                input=_atoms_pb2.GenericEventPayload,
                output=_mimir_pb2.ChomboResponse,
            ),
            "GetCurrentStateForPlayer": Endpoint(
                service_name="Mimir",
                name="GetCurrentStateForPlayer",
                function=service.GetCurrentStateForPlayer,
                input=_mimir_pb2.GetCurrentStatePayload,
                output=_mimir_pb2.GetCurrentStateResponse,
            ),
        }
