# Generated by https://github.com/Cryptact/twirpy/tree/main/protoc-gen-twirpy.  DO NOT EDIT!
# source: proto/mimir.proto

from typing import Any

from twirp.client import TwirpClient
from twirp.context import Context

from . import atoms_pb2 as _atoms_pb2
from . import mimir_pb2 as _mimir_pb2


class MimirClient(TwirpClient):
    def GetRulesets(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.EventsGetRulesetsPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _mimir_pb2.EventsGetRulesetsResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetRulesets",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.EventsGetRulesetsResponse,
            **kwargs,
        )

    def GetEvents(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.EventsGetEventsPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _mimir_pb2.EventsGetEventsResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetEvents",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.EventsGetEventsResponse,
            **kwargs,
        )

    def GetEventsById(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.EventsGetEventsByIdPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _mimir_pb2.EventsGetEventsByIdResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetEventsById",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.EventsGetEventsByIdResponse,
            **kwargs,
        )

    def GetMyEvents(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.PlayersGetMyEventsPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _mimir_pb2.PlayersGetMyEventsResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetMyEvents",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.PlayersGetMyEventsResponse,
            **kwargs,
        )

    def GetGameConfig(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GameConfig:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetGameConfig",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GameConfig,
            **kwargs,
        )

    def GetRatingTable(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.EventsGetRatingTablePayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _mimir_pb2.EventsGetRatingTableResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetRatingTable",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.EventsGetRatingTableResponse,
            **kwargs,
        )

    def GetLastGames(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.EventsGetLastGamesPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _mimir_pb2.EventsGetLastGamesResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetLastGames",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.EventsGetLastGamesResponse,
            **kwargs,
        )

    def GetGame(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericSessionPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _mimir_pb2.EventsGetGameResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetGame",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.EventsGetGameResponse,
            **kwargs,
        )

    def GetGamesSeries(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _mimir_pb2.EventsGetGamesSeriesResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetGamesSeries",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.EventsGetGamesSeriesResponse,
            **kwargs,
        )

    def GetCurrentSessions(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.PlayersGetCurrentSessionsPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _mimir_pb2.PlayersGetCurrentSessionsResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetCurrentSessions",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.PlayersGetCurrentSessionsResponse,
            **kwargs,
        )

    def GetAllRegisteredPlayers(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.EventsGetAllRegisteredPlayersPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _mimir_pb2.EventsGetAllRegisteredPlayersResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetAllRegisteredPlayers",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.EventsGetAllRegisteredPlayersResponse,
            **kwargs,
        )

    def GetTimerState(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _mimir_pb2.EventsGetTimerStateResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetTimerState",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.EventsGetTimerStateResponse,
            **kwargs,
        )

    def GetSessionOverview(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericSessionPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _mimir_pb2.GamesGetSessionOverviewResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetSessionOverview",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.GamesGetSessionOverviewResponse,
            **kwargs,
        )

    def GetPlayerStats(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.PlayersGetPlayerStatsPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _mimir_pb2.PlayersGetPlayerStatsResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetPlayerStats",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.PlayersGetPlayerStatsResponse,
            **kwargs,
        )

    def AddRound(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.GamesAddRoundPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _mimir_pb2.GamesAddRoundResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/AddRound",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.GamesAddRoundResponse,
            **kwargs,
        )

    def PreviewRound(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.GamesPreviewRoundPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _mimir_pb2.GamesPreviewRoundResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/PreviewRound",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.GamesPreviewRoundResponse,
            **kwargs,
        )

    def AddOnlineReplay(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.GamesAddOnlineReplayPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _mimir_pb2.GamesAddOnlineReplayResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/AddOnlineReplay",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.GamesAddOnlineReplayResponse,
            **kwargs,
        )

    def GetLastResults(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.PlayersGetLastResultsPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _mimir_pb2.PlayersGetLastResultsResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetLastResults",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.PlayersGetLastResultsResponse,
            **kwargs,
        )

    def GetLastRound(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.PlayersGetLastRoundPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _mimir_pb2.PlayersGetLastRoundResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetLastRound",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.PlayersGetLastRoundResponse,
            **kwargs,
        )

    def GetAllRounds(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericSessionPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _mimir_pb2.PlayersGetAllRoundsResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetAllRounds",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.PlayersGetAllRoundsResponse,
            **kwargs,
        )

    def GetLastRoundByHash(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericSessionPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _mimir_pb2.PlayersGetLastRoundByHashResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetLastRoundByHash",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.PlayersGetLastRoundByHashResponse,
            **kwargs,
        )

    def GetEventForEdit(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.EventsGetEventForEditPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _mimir_pb2.EventsGetEventForEditResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetEventForEdit",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.EventsGetEventForEditResponse,
            **kwargs,
        )

    def RebuildScoring(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/RebuildScoring",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def CreateEvent(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.EventData,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericEventPayload:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/CreateEvent",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericEventPayload,
            **kwargs,
        )

    def UpdateEvent(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.EventsUpdateEventPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/UpdateEvent",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def FinishEvent(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/FinishEvent",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def ToggleListed(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/ToggleListed",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def GetTablesState(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.EventsGetTablesStatePayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _mimir_pb2.EventsGetTablesStateResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetTablesState",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.EventsGetTablesStateResponse,
            **kwargs,
        )

    def StartTimer(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/StartTimer",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def RegisterPlayer(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.EventsRegisterPlayerPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/RegisterPlayer",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def UnregisterPlayer(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.EventsUnregisterPlayerPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/UnregisterPlayer",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def UpdatePlayerSeatingFlag(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.EventsUpdatePlayerSeatingFlagPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/UpdatePlayerSeatingFlag",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def GetAchievements(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.EventsGetAchievementsPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _mimir_pb2.EventsGetAchievementsResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetAchievements",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.EventsGetAchievementsResponse,
            **kwargs,
        )

    def ToggleHideResults(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/ToggleHideResults",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def ToggleHideAchievements(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/ToggleHideAchievements",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def UpdatePlayersLocalIds(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.EventsUpdatePlayersLocalIdsPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/UpdatePlayersLocalIds",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def UpdatePlayerReplacement(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.EventsUpdatePlayerReplacementPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/UpdatePlayerReplacement",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def UpdatePlayersTeams(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.EventsUpdatePlayersTeamsPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/UpdatePlayersTeams",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def StartGame(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.GamesStartGamePayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSessionPayload:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/StartGame",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSessionPayload,
            **kwargs,
        )

    def EndGame(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericSessionPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/EndGame",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def CancelGame(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericSessionPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/CancelGame",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def FinalizeSession(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/FinalizeSession",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def DropLastRound(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.GamesDropLastRoundPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/DropLastRound",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def DefinalizeGame(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericSessionPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/DefinalizeGame",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def AddPenalty(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.GamesAddPenaltyPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/AddPenalty",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def AddPenaltyGame(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.GamesAddPenaltyGamePayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSessionPayload:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/AddPenaltyGame",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSessionPayload,
            **kwargs,
        )

    def GetPlayer(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.PlayersGetPlayerPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _mimir_pb2.PlayersGetPlayerResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetPlayer",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.PlayersGetPlayerResponse,
            **kwargs,
        )

    def GetCurrentSeating(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _mimir_pb2.EventsGetCurrentSeatingResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetCurrentSeating",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.EventsGetCurrentSeatingResponse,
            **kwargs,
        )

    def MakeShuffledSeating(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.SeatingMakeShuffledSeatingPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/MakeShuffledSeating",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def MakeSwissSeating(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/MakeSwissSeating",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def ResetSeating(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/ResetSeating",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def GenerateSwissSeating(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.SeatingGenerateSwissSeatingPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _mimir_pb2.SeatingGenerateSwissSeatingResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GenerateSwissSeating",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.SeatingGenerateSwissSeatingResponse,
            **kwargs,
        )

    def MakeIntervalSeating(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.SeatingMakeIntervalSeatingPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/MakeIntervalSeating",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def MakePrescriptedSeating(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.SeatingMakePrescriptedSeatingPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/MakePrescriptedSeating",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def GetNextPrescriptedSeating(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _mimir_pb2.SeatingGetNextPrescriptedSeatingResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetNextPrescriptedSeating",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.SeatingGetNextPrescriptedSeatingResponse,
            **kwargs,
        )

    def GetPrescriptedEventConfig(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _mimir_pb2.EventsGetPrescriptedEventConfigResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetPrescriptedEventConfig",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.EventsGetPrescriptedEventConfigResponse,
            **kwargs,
        )

    def UpdatePrescriptedEventConfig(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.EventsUpdatePrescriptedEventConfigPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/UpdatePrescriptedEventConfig",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def InitStartingTimer(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/InitStartingTimer",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def GetStartingTimer(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _mimir_pb2.EventsGetStartingTimerResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetStartingTimer",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.EventsGetStartingTimerResponse,
            **kwargs,
        )

    def ClearStatCache(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.ClearStatCachePayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/ClearStatCache",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def ForceFinishGame(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericSessionPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/ForceFinishGame",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def AddTypedOnlineReplay(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.TypedGamesAddOnlineReplayPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _mimir_pb2.GamesAddOnlineReplayResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/AddTypedOnlineReplay",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.GamesAddOnlineReplayResponse,
            **kwargs,
        )

    def NotifyPlayersSessionStartsSoon(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/NotifyPlayersSessionStartsSoon",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def CallReferee(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.CallRefereePayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/CallReferee",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def RecalcAchievements(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/RecalcAchievements",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def RecalcPlayerStats(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/RecalcPlayerStats",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def ListPenalties(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _mimir_pb2.PenaltiesResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/ListPenalties",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.PenaltiesResponse,
            **kwargs,
        )

    def CancelPenalty(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.CancelPenaltyPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/CancelPenalty",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def AddExtraTime(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.AddExtraTimePayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _atoms_pb2.GenericSuccessResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/AddExtraTime",
            ctx=ctx,
            request=request,
            response_obj=_atoms_pb2.GenericSuccessResponse,
            **kwargs,
        )

    def ListMyPenalties(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _mimir_pb2.PenaltiesResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/ListMyPenalties",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.PenaltiesResponse,
            **kwargs,
        )

    def ListChombo(
        self,
        *,
        ctx: Context,
        request: _atoms_pb2.GenericEventPayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _mimir_pb2.ChomboResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/ListChombo",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.ChomboResponse,
            **kwargs,
        )

    def GetCurrentStateForPlayer(
        self,
        *,
        ctx: Context,
        request: _mimir_pb2.GetCurrentStatePayload,
        server_path_prefix: str = "/twirp",
        **kwargs: Any,
    ) -> _mimir_pb2.GetCurrentStateResponse:
        return self._make_request(
            url=f"{server_path_prefix}/common.Mimir/GetCurrentStateForPlayer",
            ctx=ctx,
            request=request,
            response_obj=_mimir_pb2.GetCurrentStateResponse,
            **kwargs,
        )
