"""Add initial tables

Revision ID: 02ebf819878b
Revises:
Create Date: 2025-11-21 14:17:21.716768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02ebf819878b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('p_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('telegram_name', sa.String(), nullable=True),
    sa.Column('tenhou_name', sa.String(), nullable=False),
    sa.Column('irl_name', sa.String(), nullable=True),
    sa.Column('enable_seating', sa.Integer(), nullable=False),
    sa.Column('target_tables', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('p_id'),
    sa.UniqueConstraint('telegram_id'),
    sa.UniqueConstraint('tenhou_name')
    )
    op.create_table('tables',
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Integer(), nullable=False),
    sa.Column('reveal_order', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('table_id')
    )
    op.create_table('games',
    sa.Column('game_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('started', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.table_id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('table_player_a',
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('p_id', sa.Integer(), nullable=False),
    sa.Column('seat', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['p_id'], ['players.p_id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.table_id'], ),
    sa.PrimaryKeyConstraint('table_id', 'seat')
    )
    op.create_table('game_player_a',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('p_id', sa.Integer(), nullable=False),
    sa.Column('seat', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['p_id'], ['players.p_id'], ),
    sa.PrimaryKeyConstraint('game_id', 'seat')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_player_a')
    op.drop_table('table_player_a')
    op.drop_table('games')
    op.drop_table('tables')
    op.drop_table('players')
    # ### end Alembic commands ###
