"""fixes to prepare for seating creation

Revision ID: 0730cc6ea3a4
Revises: b0c49f8a0254
Create Date: 2025-12-05 13:44:51.834731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0730cc6ea3a4'
down_revision: Union[str, Sequence[str], None] = 'b0c49f8a0254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_player_a', sa.Column('table_minimum', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('event_player_a', sa.Column('table_maximum', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('events', sa.Column('global_minimum', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('global_maximum', sa.Integer(), nullable=True))
    op.add_column('tables', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'name')
    op.drop_column('events', 'global_maximum')
    op.drop_column('events', 'global_minimum')
    op.drop_column('event_player_a', 'table_maximum')
    op.drop_column('event_player_a', 'table_minimum')
    # ### end Alembic commands ###
