"""added table reveal functionality

Revision ID: 4c1bd4a99387
Revises: 0730cc6ea3a4
Create Date: 2025-12-06 18:56:31.599904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c1bd4a99387'
down_revision: Union[str, Sequence[str], None] = '0730cc6ea3a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_player_a', sa.Column('reveal_enabled', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.drop_column('event_player_a', 'table_maximum')
    op.add_column('players', sa.Column('full_ready', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('tables', sa.Column('reveal_cached', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'reveal_cached')
    op.drop_column('players', 'full_ready')
    op.add_column('event_player_a', sa.Column('table_maximum', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('event_player_a', 'reveal_enabled')
    # ### end Alembic commands ###
