"""added chat_id and ready_players

Revision ID: 63ccbe35efae
Revises: 4c1bd4a99387
Create Date: 2025-12-07 13:39:41.123596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63ccbe35efae'
down_revision: Union[str, Sequence[str], None] = '4c1bd4a99387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ready_players',
    sa.Column('p_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['p_id'], ['players.p_id'], ),
    sa.PrimaryKeyConstraint('p_id')
    )
    op.add_column('tables', sa.Column('chat_id', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'chat_id')
    op.drop_table('ready_players')
    # ### end Alembic commands ###
