"""Add is_admin field to players

Revision ID: 7900b798994a
Revises: f6ccbb0b370a
Create Date: 2026-08-09 02:09:37.949296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7900b798994a'
down_revision: Union[str, Sequence[str], None] = 'f6ccbb0b370a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('is_admin', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'is_admin')
    # ### end Alembic commands ###
