"""removed enable_seating and target_tables player columns

Revision ID: 9145b277ee5f
Revises: 3f6fb4353010
Create Date: 2025-11-24 16:09:28.443025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9145b277ee5f'
down_revision: Union[str, Sequence[str], None] = '3f6fb4353010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'enable_seating')
    op.drop_column('players', 'target_tables')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('target_tables', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('players', sa.Column('enable_seating', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
