"""added language

Revision ID: 9cecdf2a75ec
Revises: 02ebf819878b
Create Date: 2025-11-24 15:13:01.346798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cecdf2a75ec'
down_revision: Union[str, Sequence[str], None] = '02ebf819878b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('language', sa.String(), server_default='ru', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'language')
    # ### end Alembic commands ###
