"""added_event_and_player_pantheon_ids

Revision ID: 9dc415c5abbf
Revises: aedf3f985ad9
Create Date: 2026-03-29 14:02:41.213219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dc415c5abbf'
down_revision: Union[str, Sequence[str], None] = 'aedf3f985ad9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_player_a', sa.Column('leaderboard_group', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('events', sa.Column('pantheon_id', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('pantheon_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'pantheon_id')
    op.drop_column('events', 'pantheon_id')
    op.drop_column('event_player_a', 'leaderboard_group')
    # ### end Alembic commands ###
