"""Added deadline groups

Revision ID: aedf3f985ad9
Revises: feb953299728
Create Date: 2026-03-27 22:33:26.778765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aedf3f985ad9'
down_revision: Union[str, Sequence[str], None] = 'feb953299728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('deadline_group', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'deadline_group')
    # ### end Alembic commands ###
