"""fixed event_player primary key

Revision ID: b0c49f8a0254
Revises: e571cb8a92bf
Create Date: 2025-12-03 07:35:22.019459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0c49f8a0254'
down_revision: Union[str, Sequence[str], None] = 'e571cb8a92bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('event_player_a_pkey', 'event_player_a', type_='primary')
    op.create_primary_key('event_player_a_pkey', 'event_player_a', ['event_id', 'p_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('event_player_a_pkey', 'event_player_a', type_='primary')
    op.create_primary_key('event_player_a_pkey', 'event_player_a', ['event_id'])
    # ### end Alembic commands ###
