"""leaderboard_fields_for_events

Revision ID: dda2bb92f1ae
Revises: 9dc415c5abbf
Create Date: 2026-04-07 23:57:10.262997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dda2bb92f1ae'
down_revision: Union[str, Sequence[str], None] = '9dc415c5abbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('leaderboard_name', sa.String(), nullable=True))
    op.add_column('events', sa.Column('short_name', sa.String(), nullable=True))
    op.add_column('events', sa.Column('leaderboard_specs', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'leaderboard_specs')
    op.drop_column('events', 'short_name')
    op.drop_column('events', 'leaderboard_name')
    # ### end Alembic commands ###
