"""added events table

Revision ID: dffc783dec25
Revises: 9145b277ee5f
Create Date: 2025-12-01 09:35:56.537256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dffc783dec25'
down_revision: Union[str, Sequence[str], None] = '9145b277ee5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('signup', sa.Integer(), nullable=True),
    sa.Column('started', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
