"""added event_player

Revision ID: e571cb8a92bf
Revises: da059247fe79
Create Date: 2025-12-02 15:42:32.932606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e571cb8a92bf'
down_revision: Union[str, Sequence[str], None] = 'da059247fe79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_player_a',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('p_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['p_id'], ['players.p_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.add_column('tables', sa.Column('event_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tables', 'events', ['event_id'], ['event_id'])
    op.drop_column('tables', 'reveal_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('reveal_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tables', type_='foreignkey')
    op.drop_column('tables', 'event_id')
    op.drop_table('event_player_a')
    # ### end Alembic commands ###
