"""separate table_time into new table

Revision ID: f6ccbb0b370a
Revises: dda2bb92f1ae
Create Date: 2026-04-10 13:30:32.303256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6ccbb0b370a'
down_revision: Union[str, Sequence[str], None] = 'dda2bb92f1ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_times',
    sa.Column('table_time_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('games', sa.Integer(), nullable=False),
    sa.Column('need_reminder', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.table_id'], ),
    sa.PrimaryKeyConstraint('table_time_id')
    )
    op.drop_column('tables', 'time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('time', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table('table_times')
    # ### end Alembic commands ###
